import React, { useState } from 'react';
import { Search, BrainCircuit, Download, FileText, AlertTriangle, CheckCircle, Navigation, Clock, Gauge, Activity, ShieldCheck, Loader2 } from 'lucide-react';
import './Reports.css';

const MOCK_TRACKS = [
  { id: 'T-001', name: 'Delhi – Amritsar', zone: 'Northern', length: '448 km', lastScan: '2026-08-18', riskScore: 'Low' },
  { id: 'NR-002', name: 'Delhi – Jaipur – Ahmedabad', zone: 'Northern', length: '934 km', lastScan: '2026-07-22', riskScore: 'Medium' },
  { id: 'WR-001', name: 'Mumbai – Pune Corridor', zone: 'Western', length: '150 km', lastScan: '2026-08-20', riskScore: 'High' },
  { id: 'SR-002', name: 'Chennai – Vijayawada', zone: 'Southern', length: '430 km', lastScan: '2026-07-31', riskScore: 'Low' },
  { id: 'ER-005', name: 'Kolkata – Bhubaneswar', zone: 'Eastern', length: '440 km', lastScan: '2026-08-15', riskScore: 'Medium' }
];

const Reports = () => {
  const [search, setSearch] = useState('');
  const [selectedTrack, setSelectedTrack] = useState(null);
  const [isDownloading, setIsDownloading] = useState(false);

  const filteredTracks = MOCK_TRACKS.filter(t => 
    t.id.toLowerCase().includes(search.toLowerCase()) || 
    t.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleDownload = () => {
    setIsDownloading(true);
    setTimeout(() => {
      setIsDownloading(false);
      alert('Report successfully downloaded to your device as PDF.');
    }, 2000);
  };

  if (selectedTrack) {
    return (
      <div className="reports-page">
        <div className="reports-header">
          <button 
            onClick={() => setSelectedTrack(null)} 
            style={{ background: 'transparent', border: 'none', color: 'var(--color-text-mut)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '16px', fontSize: '14px' }}
          >
            ← Back to All Reports
          </button>
          <h2 className="reports-title"><FileText size={24} /> AI Diagnostic Report: {selectedTrack.id}</h2>
          <p className="reports-subtitle">{selectedTrack.name} · {selectedTrack.zone} Zone</p>
        </div>

        <div className="ai-report-container">
          {/* AI Header */}
          <div className="ai-header-card">
            <div className="ai-badge">
              <BrainCircuit size={14} />
              Generated by AXION AI
            </div>
            <p className="ai-summary-text">
              AXION's predictive model has analyzed 4.2 million data points collected during the last pass of the Dolphin Mk IV on {selectedTrack.lastScan}. 
              The system predicts an <span className="ai-summary-highlight">85% probability of rail buckling</span> within the next 14 days near km 48 due to elevated thermal stress and micro-fracture propagation. 
              Immediate preventive maintenance is highly recommended to avoid service disruption.
            </p>
          </div>

          <div className="report-grid">
            {/* Defects & Anomalies */}
            <div className="report-card">
              <h3 className="report-card-title"><AlertTriangle size={16} /> Automated Defect Detection</h3>
              <div className="defect-list">
                <div className="defect-item critical">
                  <Activity size={18} className="defect-icon" />
                  <div>
                    <h4 className="defect-title">Hairline Micro-fracture (km 48.2)</h4>
                    <p className="defect-desc">Acoustic signature variation of +4dB indicates sub-surface web fracturing. Classified as CRITICAL by AI categorization model.</p>
                    <div className="defect-meta"><span>Confidence: 98.4%</span><span>Action: Replace</span></div>
                  </div>
                </div>
                <div className="defect-item warning">
                  <Gauge size={18} className="defect-icon" />
                  <div>
                    <h4 className="defect-title">Gauge Deviation (km 52.0)</h4>
                    <p className="defect-desc">LiDAR scan detected a +4mm lateral gauge deviation across a 200m section. Likely caused by ballast degradation.</p>
                    <div className="defect-meta"><span>Confidence: 92.1%</span><span>Action: Tamping Required</span></div>
                  </div>
                </div>
                <div className="defect-item info">
                  <CheckCircle size={18} className="defect-icon" />
                  <div>
                    <h4 className="defect-title">Fastener Integrity</h4>
                    <p className="defect-desc">All Pandrol clips and sleepers are seated correctly within normal tolerances.</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Fleet Health & Prediction */}
            <div className="report-card" style={{ display: 'flex', flexDirection: 'column' }}>
              <h3 className="report-card-title"><ShieldCheck size={16} /> Track Health Score</h3>
              
              <div className="prediction-score">
                <div className="ps-value" style={{ color: selectedTrack.riskScore === 'High' ? '#ef4444' : selectedTrack.riskScore === 'Medium' ? '#f59e0b' : '#10b981' }}>
                  {selectedTrack.riskScore === 'High' ? '42/100' : selectedTrack.riskScore === 'Medium' ? '68/100' : '94/100'}
                </div>
                <p className="ps-label">Overall Integrity Index</p>
              </div>

              <div style={{ marginTop: 'auto', borderTop: '1px solid var(--color-border)', paddingTop: '16px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '13px', color: 'var(--color-text-mut)', marginBottom: '8px' }}>
                  <span>Next Maintenance Cycle</span>
                  <span style={{ color: 'var(--color-text)' }}>In 12 days</span>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '13px', color: 'var(--color-text-mut)' }}>
                  <span>Estimated Downtime</span>
                  <span style={{ color: 'var(--color-text)' }}>4 Hours</span>
                </div>
              </div>
            </div>
          </div>

          <div className="report-actions">
            <button className="btn-download" onClick={handleDownload} disabled={isDownloading}>
              {isDownloading ? (
                <><Loader2 size={16} className="download-spinner" /> Compiling Report...</>
              ) : (
                <><Download size={16} /> Download Full PDF</>
              )}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="reports-page">
      <div className="reports-header">
        <h2 className="reports-title"><FileText size={24} /> AI Inspection Reports</h2>
        <p className="reports-subtitle">Select a track section to view detailed predictive maintenance reports generated by AXION AI.</p>
      </div>

      <div className="reports-search-bar">
        <Search size={18} style={{ color: 'var(--color-text-mut)' }} />
        <input 
          type="text" 
          placeholder="Search by Track ID or Name"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      <div className="track-list-grid">
        {filteredTracks.map(track => (
          <div key={track.id} className="track-list-card" onClick={() => setSelectedTrack(track)}>
            <div className="tlc-header">
              <h3 className="tlc-title">{track.id}</h3>
              <span className={`sdp-status-tag ${track.riskScore === 'Low' ? 'good' : track.riskScore === 'Medium' ? 'warn' : 'crit'}`}>
                Risk: {track.riskScore}
              </span>
            </div>
            <p className="tlc-zone">{track.name}</p>
            <div className="tlc-stats">
              <div className="tlc-stat"><Navigation size={14} /> {track.length}</div>
              <div className="tlc-stat"><Clock size={14} /> {track.lastScan}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Reports;
